SELECT P.NOME, C.NUMERO
FROM PESSOA P
RIGHT OUTER JOIN CONTATO C ON (C.ID_PESSOA = P.ID_PESSOA);

SELECT P.NOME, pxpe.ID_PESSOA, pxpe.ID_ENDERECO, ep.ESTADO, ep.CIDADE 
FROM PESSOA P
RIGHT OUTER JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON pxpe.ID_PESSOA = P.ID_PESSOA
RIGHT OUTER JOIN ENDERECO_PESSOA ep ON ep.ID_ENDERECO = pxpe.ID_ENDERECO

SELECT P.NOME, C.NUMERO, pxpe.ID_ENDERECO, ep.CIDADE, ep.PAIS, ep.ESTADO
FROM PESSOA P
RIGHT OUTER JOIN CONTATO C ON (C.ID_PESSOA = P.ID_PESSOA)
RIGHT OUTER JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON (PXPE.ID_PESSOA = P.ID_PESSOA)
RIGHT OUTER JOIN ENDERECO_PESSOA ep ON (EP.ID_ENDERECO = PXPE.ID_ENDERECO)

SELECT P.ID_PESSOA, P.NOME, C.NUMERO, C.DESCRICAO
FROM PESSOA P
FULL OUTER JOIN CONTATO c ON (C.ID_PESSOA = P.ID_PESSOA)
	          
SELECT P.ID_PESSOA, P. NOME, PXPE.ID_PESSOA, ep.CEP, ep.CIDADE, ep.ESTADO, ep.PAIS
FROM PESSOA P
FULL OUTER JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON (PXPE.ID_PESSOA = P.ID_PESSOA)
FULL OUTER JOIN ENDERECO_PESSOA ep ON (EP.ID_ENDERECO = PXPE.ID_ENDERECO)

SELECT P.NOME, C.NUMERO, PXPE.ID_PESSOA, PXPE.ID_ENDERECO, ep.CEP, ep.CIDADE, ep.PAIS, ep.ESTADO 
FROM PESSOA P
FULL JOIN CONTATO c ON c.ID_PESSOA = p.ID_PESSOA 
FULL JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON pxpe.ID_PESSOA = p.ID_PESSOA
FULL JOIN ENDERECO_PESSOA ep ON ep.ID_ENDERECO = pxpe.ID_ENDERECO;
	          		 
SELECT P.ID_PESSOA, P.NOME AS "PESSOAS C/ ENDEREÇOS"	
FROM PESSOA P
WHERE EXISTS (
	SELECT PXPE.ID_PESSOA  
	FROM PESSOA_X_PESSOA_ENDERECO pxpe
	WHERE PXPE.ID_PESSOA = P.ID_PESSOA
)

SELECT P.ID_PESSOA, P.NOME, ep.ID_ENDERECO, ep.LOGRADOURO  
FROM PESSOA P, ENDERECO_PESSOA ep  
WHERE EXISTS (SELECT pxpe.ID_PESSOA 
FROM PESSOA_X_PESSOA_ENDERECO pxpe
WHERE pxpe.ID_PESSOA = p.ID_PESSOA);
